# Generated by Django 3.2.3 on 2021-06-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='업로드 파일'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='업로드 이미지'),
        ),
    ]
