# Generated by Django 3.2.3 on 2021-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_no', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='제품번호')),
                ('item_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('item_price', models.PositiveIntegerField(verbose_name='제품가격')),
            ],
        ),
    ]
